'use server';

import { generateWorksheet } from '@/lib/ai/worksheet-generator';
import { createAssignment } from '@/lib/supabase/mutations';
import { WorksheetData } from '@/types';
import { revalidatePath } from 'next/cache';

export async function generateWorksheetAction(
  topic: string, 
  age: string | number, 
  instructions: string
) {
  try {
    const data = await generateWorksheet(topic, age, instructions);
    return { success: true, data };
  } catch (error) {
    console.error('Worksheet generation failed:', error);
    return { success: false, error: 'Failed to generate worksheet' };
  }
}

export async function saveWorksheetAssignmentAction(
  worksheetData: WorksheetData,
  title: string,
  kidIds: string[] = [] // Optional: auto-assign to kids?
) {
  try {
    console.log('=== WORKSHEET SAVE DEBUG ===');
    console.log('Title:', title);
    console.log('Worksheet Data Keys:', Object.keys(worksheetData));
    console.log('Worksheet Data:', JSON.stringify(worksheetData).slice(0, 500));
    
    // Create an assignment item with the worksheet data
    const assignment = await createAssignment({
      title: title,
      type: 'worksheet',
      deliverable: 'Completed Worksheet',
      rubric: [],
      steps: [{ text: 'Print the attached worksheet' }, { text: 'Complete all questions' }],
      parent_notes: 'Generated by AI',
      estimated_minutes: 20,
      tags: ['worksheet', 'ai-generated'],
      links: [],
      is_template: true,
      worksheet_data: worksheetData
    });

    console.log('=== ASSIGNMENT CREATED ===');
    console.log('Assignment ID:', assignment?.id);

    revalidatePath('/parent/assignments');
    revalidatePath('/parent/lessons');
    
    return { success: true, assignmentId: assignment.id };
  } catch (error) {
    console.error('=== WORKSHEET SAVE ERROR ===');
    console.error('Error type:', typeof error);
    console.error('Error:', error);
    
    // Extract detailed error info
    let errorMessage = 'Unknown error';
    if (error instanceof Error) {
      errorMessage = error.message;
    } else if (typeof error === 'object' && error !== null) {
      errorMessage = JSON.stringify(error);
    }
    
    return { success: false, error: errorMessage };
  }
}

