'use server';

import { generateWorksheet } from '@/lib/ai/worksheet-generator';
import { createAssignment } from '@/lib/supabase/mutations';
import { WorksheetData } from '@/types';
import { revalidatePath } from 'next/cache';

export async function generateWorksheetAction(
  topic: string, 
  age: string | number, 
  instructions: string
) {
  try {
    const data = await generateWorksheet(topic, age, instructions);
    return { success: true, data };
  } catch (error) {
    console.error('Worksheet generation failed:', error);
    return { success: false, error: 'Failed to generate worksheet' };
  }
}

export async function saveWorksheetAssignmentAction(
  worksheetData: WorksheetData,
  title: string,
  kidIds: string[] = [] // Optional: auto-assign to kids?
) {
  try {
    console.log('Saving worksheet assignment:', { title, worksheetDataKeys: Object.keys(worksheetData) });
    
    // Create an assignment item with the worksheet data
    const assignment = await createAssignment({
      title: title,
      type: 'worksheet',
      deliverable: 'Completed Worksheet',
      rubric: [],
      steps: [{ text: 'Print the attached worksheet' }, { text: 'Complete all questions' }],
      parent_notes: 'Generated by AI',
      estimated_minutes: 20,
      tags: ['worksheet', 'ai-generated'],
      links: [],
      is_template: true, // Changed to true so it appears in library
      worksheet_data: worksheetData
    });

    console.log('Assignment created:', assignment);

    revalidatePath('/parent/assignments');
    revalidatePath('/parent/lessons');
    
    return { success: true, assignmentId: assignment.id };
  } catch (error) {
    console.error('Failed to save worksheet assignment:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    return { success: false, error: `Failed to save assignment: ${errorMessage}` };
  }
}
